#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 1 2 3 4
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rate 144 --rotate normal --output HDMI-A-0 --mode 2560x1080 --rate 75 --rotate right --right-of DisplayPort-0
bspc monitor HDMI-A-0 -d 5 6 7 8

Xcursor.size: 8
xrdb ~/.Xresources

bspc config border_width         2
bspc config window_gap           18
bspc config top_padding          34

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_color "#282828"
bspc config focused_border_color "#ffd573"
bspc config normal_border_color "#282828"
bspc config presel_feedback_color "#282828"
bspc config urgent_border_color "#282828"
bspc config focused_locked_border_color "#282828"
bspc config normal_sticky_border_color "#282828"
bspc config normal_locked_border_color "#282828"
bspc config focused_sticky_border_color "#282828"
bspc config active_border_color "#282828"
bspc config border_radius 10 # NOTE! Without something like Picom it looks bad. Picom has "fading" option, that works like anti-aliasing for border. Look for ~/.config/picom/picom.conf

#!/bin/sh

#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
$HOME/.config/polybar/launch.sh
